### ISSUE TITLE
region should default to env

### ISSUE THREAD

**Issue by willfarrell** [hsz/middy-secrets#1]
Saw your post at https://github.com/middyjs/middy/issues/151#issuecomment-381426801, thanks for creating this.

Did a quick look over:
- [x] region should defualt to ENV `AWS_REGION` || `AWS_DEFAULT_REGION` [Docs](https://github.com/middyjs/middy/issues/151#issuecomment-381426801)
- [x] secrets endpoint should also default to the region env, unless overwritten.
- [x] docs shoudl show `endpoint` as a valid option

Let me know if you'd like a PR for this.

**Comment by hsz** [comment]
Thank you for your ticket!

Indeed, region should not be set to any value and taken from env variables just with the possibility to overwrite them with options.
My endpoint has been removed, library will discover it automatically using `AWS_REGION`.
I've updated documentation just with a mention that all AWS options can be overwritten (with link to AWS docs).

It's published as v0.1.1

**Comment by willfarrell** [comment]
Looks much cleaner now. One last thing I noticed, I promise.

```
try {
        const response = JSON.parse(data.SecretString || '{}');
        resolve(response);
      } catch (e) {
        reject(err);
      }
```

Is this try catch necessary? `data` is coming from AWS, I find it odd that it would fail to parse requiring this catch to exist.

PS What kind of latency have you observed with AWS Secrets?

**Comment by hsz** [comment]
This try-catch is kinda required because it's possible to set in AWS SM malformed JSON, like:

![image](https://user-images.githubusercontent.com/108333/38812528-cab5b288-418c-11e8-9922-7320bd7d432a.png)

Regarding latency - I didn't have opportunity to test it yet. I'm building application from scratch and decided to use SM to speed up this process.

**Comment by willfarrell** [comment]
I would submit a support ticket for that. Good catch.
